PROGRAM RICKER_TESTE
IMPLICIT NONE
REAL :: FCORTE_ANA,DT
INTEGER :: L
!
REAL, POINTER :: F(:)
!
INTEGER :: I,N,K
REAL    :: PI,FC,TF
REAL    :: AUX1,AUX2,AUX3
!
FCORTE_ANA = 60
DT = 2E-3
!
PI = 4*ATAN(1.0)
FC = FCORTE_ANA/(3*SQRT(PI))  ! FREQUENCIA DE CORTE DIGITAL
TF = 2*SQRT(PI)/FC    ! INSTANTE DE TEMPO DA ULTIMA AMOSTRA
N  = NINT(TF/DT)
!
ALLOCATE(F(-N:N))
!
AUX1 = PI*PI*PI * FC*FC
F(0) = 1 !(1-AUX1*TF*TF-AUX1*TF*TF)*EXP(-AUX1*TF*TF)
!	
DO I = 1,N
	AUX2  = (I*DT)*(I*DT)
	AUX3  = AUX1*AUX2
        F(I) = (1-AUX3-AUX3)*EXP(-AUX3)
        F(-I) = F(I)
ENDDO
WRITE(*,*) 2*N+1
OPEN(10, FILE='FONTE.BIN', STATUS="UNKNOWN", FORM="UNFORMATTED", ACCESS="DIRECT", RECL=(2*N+1)*4)
WRITE(10,REC=1) (F(K),K=-N,N) 
END PROGRAM RICKER_TESTE

